server:
  port: 8081
spring:
  application:
    name: itemservice
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
  rabbitmq:
    host: 192.168.231.129 #主机名
    port: 5672 #端口
    virtual-host: / #虚拟主机
    username: itcast #用户名
    password: 123321 #密码
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS